sudo: required
services:
  - docker

before_install:
  - docker build -t client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true client-test npm test

after_success:
  - docker build -t multi-client ./client/Dockerfile
  - docker build -t multi-nginx ./nginx/Dockerfile
  - docker build -t multi-server ./server/Dockerfile
  - docker build -t multi-worker ./worker/Dockerfile
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push the images to docker hub
  - docker push multi-client
  - docker push multi-nginx
  - docker push multi-server
  - docker push multi-worker
