sudo: required
services:
  - docker

before_install:
  - docker build -t pgsoncada/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pgsoncada/client-test npm test

after_success:
  - docker build -t princeoncada/multi-client ./client/Dockerfile
  - docker build -t princeoncada/multi-nginx ./nginx/Dockerfile
  - docker build -t princeoncada/multi-server ./server/Dockerfile
  - docker build -t princeoncada/multi-worker ./worker/Dockerfile
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io

  # Push the images to docker hub
  - docker tag princeoncada/multi-client pgsoncada/multi-client
  - docker push pgsoncada/multi-client
  - docker push pgsoncada/multi-nginx
  - docker push pgsoncada/multi-server
  - docker push pgsoncada/multi-worker
